### ISSUE TITLE
add raw ore

### ISSUE THREAD

**Issue by feanchy** [PowerNukkit/PowerNukkit#1374] opened 2022-07-05 16:25 UTC
# ❇ Feature Request

### 📸 Screenshots / Videos
[<!-- ✍ (https://youtu.be/LfSvJFUYhwM)

### ✔ Expected Behavior
<!-- ✍ instead of iron, copper, gold ore, the unprocessed ore that I listed should fall out

### ❌ Actual Behavior
<!-- ✍ ordinary ore fell out :/

**Comment by alikindsys** [comment] 2022-07-09 18:11
Duplicate of #1373

**Closed as not planned by alikindsys** 2022-07-09 18:11 UTC
Labels: Resolution: duplicate, Type: enhancement
