### ISSUE TITLE
Shield / Offhand

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#1031] opened 2021-04-05 08:07 UTC
# 🐞 I found a bug
 If you hold a shield off-hand, it will not display correctly graphically.

### ▶ Steps to Reproduce

1. Hold a shield off-hand
2. Now you can see this following Graphic Bug

### 📋 Debug information

* PowerNukkit version: (b7f4ffa)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment] 2021-04-05 08:08
![20210405_100012.jpg](https://user-images.githubusercontent.com/59027482/113552728-d8fec200-95f6-11eb-9fc3-70ae0586e49a.jpg)

**Comment by joserobjr** [comment] 2021-06-26 17:45
Closing as duplicate of #1156, keeping the other one because the other has more information.

**Closed by joserobjr** 2021-06-26 17:45 UTC
Labels: Type: bug
