### ISSUE TITLE
Nothing can be renamed in an anvil.

### ISSUE THREAD

**Issue by MrRazamataz** [PowerNukkit/PowerNukkit#839] opened 2020-12-19 10:01 UTC
# 🐞 I found a bug
Nothing can be renamed in an anvil.

### 📸 Screenshots / Videos

https://youtu.be/gNGCGt0O418

### 📋 Debug information
https://debugpaste.powernukkit.org/pastes/wahataxana

**Comment by MonoAdrian23** [comment] 2020-12-19 11:52
Duplicate of #829

**Closed** 2020-12-19 14:07 UTC
Labels: Resolution: duplicate, Type: bug
