### ISSUE TITLE
An exception occurred in RakNet (Server)  io.netty.channel.unix.Errors$NativeIoException: sendToAddress(..) failed: Invalid argument

### ISSUE THREAD

**Issue by PocketMiner92** [PowerNukkit/PowerNukkit#1337] opened 2022-04-19 05:44 UTC
# 🐞 I found a bug
 Network Listener - #12] ERROR - An exception occurred in RakNet (Server)
io.netty.channel.unix.Errors$NativeIoException: sendToAddress(..) failed: Invalid argument

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-0bdd3ab)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by PocketMiner92** [comment] 2022-04-19 09:38
Now this Error spams 500 Times
Without Players
And Crash the server

**Comment by PocketMiner92** [comment] 2022-04-19 11:58
@joserobjr I Hope you can Help
Its Important
We do nothing, it Happens since i use Fakeinventorys for Powernukkit.

**Comment by PleaseInsertNameHere** [comment] 2022-04-19 14:57
Could you please provide more information? Which version of FakeInventories are you using? Is there any more information provided in the recieved exception?

**Comment by PocketMiner92** [comment] 2022-04-19 15:01
Fakeinventorys 1.0.3 from Powernukkits Plugin Page.
But this Happens without any Players.
Ramdomly in Console.

**Comment by PocketMiner92** [comment] 2022-04-19 15:04
Its all the Same
1000 Times the same Message in Console

**Comment by PleaseInsertNameHere** [comment] 2022-04-19 15:05
So its just
`Network Listener - #12] ERROR - An exception occurred in RakNet (Server)
io.netty.channel.unix.Errors$NativeIoException: sendToAddress(..) failed: Invalid argument`?

**Comment by PocketMiner92** [comment] 2022-04-19 15:09
![20220419_170905.jpg](https://user-images.githubusercontent.com/96331694/164036014-fc437c85-4e0e-4099-816f-d2553b1b19b0.jpg)

Only this

**Comment by PleaseInsertNameHere** [comment] 2022-04-19 15:11
Which plugins are using FakeInventories on your server?

**Comment by PocketMiner92** [comment] 2022-04-19 15:13
Craft, AuctionHouse, Enderchest, Invsee

**Comment by PocketMiner92** [comment] 2022-04-19 15:15
Yes

**Comment by PocketMiner92** [comment] 2022-04-19 15:25
Yes
I think it haves nothing to do with this

**Comment by joserobjr** [comment] 2022-04-19 15:28
Closing as duplicated of #1056 please let's keep our effort to resolve this problem there

**Comment by joserobjr** [comment] 2022-04-19 15:31
Reopening because i derped, it's `invalid argument` and not `operation is not permitted`, might be another OS related issue, but a different one from #1056

**Comment by PleaseInsertNameHere** [comment] 2022-04-19 15:35
> Yes I think it haves nothing to do with this

I also don't think so, just wanted to make sure. What I know is that .sendToAddress() is a method of `io.netty.channel.unix.Socket`, no idea why this is causing a problem

**Comment by PocketMiner92** [comment] 2022-04-19 15:57
I have contact Minehub and the Support say its a Issue from Powernukkit

**Comment by PleaseInsertNameHere** [comment] 2022-04-19 16:04
Can you check which PN version your server is running at? (/version)
I want to check if I can reproduce this error in any way.

**Comment by PocketMiner92** [comment] 2022-04-19 16:09
Now i use the latest

(git-926cab2)

**Comment by PocketMiner92** [comment] 2022-04-19 16:22
It say's open or filtered

**Comment by PocketMiner92** [comment] 2022-04-20 07:56
Hmmm
I have delete the world and Nether.
Looks Like the Error is gone

**Comment by PocketMiner92** [comment] 2022-04-20 09:12
World Corrupted
Close because its fixed

**Comment by PocketMiner92** [comment] 2022-04-20 12:46
Powernukkit Issue.

**Comment by PocketMiner92** [comment] 2022-04-22 15:41
Fixed because server-ip=
Was empty.

It was deleted by itself lol

**Closed** 2022-04-22 15:40 UTC
Labels: Type: envionment
