### ISSUE TITLE
Piston bug (chest)

### ISSUE THREAD

**Issue by Iktaniyalol** [PowerNukkit/PowerNukkit#413] opened 2020-07-26 16:37 UTC
# 🐞 I found a bug

### 📸 Screenshots / Videos

video: https://youtu.be/HbiITExg8Fc

### ▶ Steps to Reproduce

1. Place piston
2. Place any blocks
3. Place chest (I think you can use any container block)
4. Bug

### ✔ Expected Behavior

Piston should move chests with keeping inventory

### ❌ Actual Behavior

Chest inventory is empty after move by piston

### 📋 Debug information

* PowerNukkit version: ✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by PocketMiner82** [comment] 2020-07-31 10:59
I fixed this with #359. There was an issue with blockentities behind the first blockentity of the piston.

**Comment by joserobjr** [comment] 2020-08-08 22:56
I confirm it was fixed by PocketMiner82 at #359 , I couldn't reproduce it in 1.3.1.2-PN-SNAPSHOT.

Thank you for the report 👍

**Closed by joserobjr** 2020-08-08 22:56 UTC
Labels: Type: bug
