### ISSUE TITLE
Redstone comparator causes the server to crash

### ISSUE THREAD

**Issue by whes1015** [PowerNukkit/PowerNukkit#1182] opened 2021-07-06 19:12 UTC
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Redstone comparator causes the server to crash

### 📋 Debug information

* PowerNukkit version: 1.5.2.0-PN✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by Gabriel8579** [comment] 2021-08-29 11:44
Can you provide the /debugpaste upload command result?

**Comment by FlamingKnight** [comment] 2021-08-29 12:49
Is it the same as this? https://github.com/PowerNukkit/PowerNukkit/pull/1204

**Comment by roridev** [comment] 2021-10-24 01:49
Duplicate of #1174. 
Will be solved by #1204.

**Closed by roridev** 2021-10-24 01:49 UTC
Labels: Type: bug, Status: Awaiting Response
