### ISSUE TITLE
Boats

### ISSUE THREAD

**Issue by RizenSoulja** [PowerNukkit/PowerNukkit#863] opened 2020-12-24 22:11 UTC
# 🐞 I found a bug
<!-- 
👉 Using the latest version of PowerNukkit. Found that if you ride in a boat, you'll slowly start to sink.

### ▶ Steps to Reproduce
1. Place a boat in water
2. Get in boat
3. Ride around deep waters for a bit
4. Slowly start to sink as your riding

**Comment by RizenSoulja** [comment] 2020-12-26 01:21
1.4.0.0-PN-ALPHA.2 (recommended)

**Comment by Jl1mbo** [comment] 2020-12-26 05:41
I ask you to reopen the question, but in the form that is issued when creating

**Comment by RORIdev** [comment] 2020-12-26 15:49
Duplicate of #853

**Closed by RORIdev** 2020-12-26 15:49 UTC
Labels: Type: bug
