### ISSUE TITLE
Debugpaste doenst work

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#834] opened 2020-12-17 18:19 UTC
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Run command '/debugpaste'
3. Put '....' at '...'

### ✔ Expected Behavior
 java.io.IOException: Server returned HTTP response code: 503 for URL: https://hastebin.com/documents
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894) ~[?:1.8.0_212]
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_212]
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_212]
at cn.nukkit.utils.HastebinUtility.upload(HastebinUtility.java:30) ~[powernukkit-stable.jar:?]
at cn.nukkit.command.defaults.DebugPasteCommand$1.onRun(DebugPasteCommand.java:40) [powernukkit-stable.jar:?]
at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) [powernukkit-stable.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

### 📋 Debug information

* PowerNukkit version: 1.4.0.0 Alpha 2 Latest
* Debug link: Doesnt work 
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment] 2020-12-18 11:31
(git-bb4dff3)

**Comment by MrRazamataz** [comment] 2020-12-19 09:54
I think this just means hastebin wasnt responding, try again later. If it is a constant issue, I may be wrong.

**Comment by MonoAdrian23** [comment] 2020-12-19 11:51
So, i try it again.
Same Error.

**Comment by RORIdev** [comment] 2021-01-03 15:25
Duplicate of #535. will be fixed by #681

**Closed by RORIdev** 2021-01-03 15:25 UTC
Labels: Type: bug
