### ISSUE TITLE
Players getting random disconnections

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#858] opened 2020-12-22 19:19 UTC
# 🐞 I found a bug

### ▶ Steps to Reproduce

1. Join Server
2. I dont know why this Happens 
3. Its weird
4. See error (Please read my Hastebin, i have posted on Discord)
5. https://debugpaste.powernukkit.org/pastes/qulidokazu

### 📋 Debug information

* PowerNukkit version: 1.4.0.0 Alpha 2 Release Today
* Debug link: https://debugpaste.powernukkit.org/pastes/bewosebime
* Timings link (if relevant): ✍

**Comment by MrClean1337** [comment] 2020-12-22 19:29
This bug is also in bleeding-1.3
I tracked that problem now !

20:07:06 [WARN ] Received packet violation warning for packet MOVE_ENTITY_ABSOLUTE_PACKET: PacketViolationWarningPacket(type=MALFORMED_PACKET, severity=FINAL_WARNING, packetId=18, context=)
20:07:06 [INFO ] MrClean2349[/127.0.0.1:44219] hat sich ausgeloggt Disconnected from Server

We 3 players were standing still at spawn.
Nothing happened.

I just jumped. 2 of us got kicked. (Just a space key, no rotation or something else)

**Comment by joserobjr** [comment] 2020-12-22 19:39
```java
Exception while sending packets to <player>
java.lang.ArrayIndexOutOfBoundsException: null
at cn.nukkit.utils.BinaryStream.put(BinaryStream.java:109) ~[powernukkit-stable.jar:?]
at cn.nukkit.utils.BinaryStream.putSlot(BinaryStream.java:504) ~[powernukkit-stable.jar:?]
at cn.nukkit.network.protocol.MobEquipmentPacket.encode(MobEquipmentPacket.java:37) ~[powernukkit-stable.jar:?]
at cn.nukkit.network.RakNetInterface$NukkitRakNetSession.sendPackets(RakNetInterface.java:323) ~[powernukkit-stable.jar:?]
at cn.nukkit.network.RakNetInterface$NukkitRakNetSession.sendOutbound(RakNetInterface.java:304) ~[powernukkit-stable.jar:?]
at cn.nukkit.network.RakNetInterface$NukkitRakNetSession.access$700(RakNetInterface.java:253) ~[powernukkit-stable.jar:?]
at cn.nukkit.network.RakNetInterface.lambda$new$0(RakNetInterface.java:80) ~[powernukkit-stable.jar:?]
at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [powernukkit-stable.jar:?]
at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:176) [powernukkit-stable.jar:?]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [powernukkit-stable.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [powernukkit-stable.jar:?]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [powernukkit-stable.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [powernukkit-stable.jar:?]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [powernukkit-stable.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by joserobjr** [comment] 2021-01-05 01:55
```java
@exception  IndexOutOfBoundsException  if copying would cause
     *               access of data outside array bounds.
```

**Comment by joserobjr** [comment] 2021-01-05 02:01
I think the only way that could happen with this method would be if the BinaryStream gets modified concurrently, so the count field value changes between the `ensureCapacity` and the `arraycopy` calls, and I think that it was solved by #882
```java
public void put(byte[] bytes) {
        if (bytes == null) {
            return;
        }

        this.ensureCapacity(this.count + bytes.length);

        System.arraycopy(bytes, 0, this.buffer, this.count, bytes.length);
        this.count += bytes.length;
    }
```

**Comment by AntonPPDS** [comment] 2021-01-05 21:10
Is it possible that a packet in different threads will simultaneously start encoding and an awkward mixture will turn out from the buffer? Then it's not really resorved because there is still a chance of repeating the encoding in a different thread until the previous one completes.

**Comment by MrClean1337** [comment] 2021-01-05 22:32
Is this issue now fixed ? If so, close o.O

**Comment by RORIdev** [comment] 2021-01-05 22:36
> Is it possible that a packet in different threads will simultaneously start encoding and an awkward mixture will turn out from the buffer? Then it's not really resorved because there is still a chance of repeating the encoding in a different thread until the previous one completes.

We had the idea that it could be some wierd concurrency issues, and jose merged a PR that brings some fixes from upstream. If there are some other wierd concurrency problems on PN's code please point those out so we can fix them, and by consequence of that close this issue.

**Comment by AntonPPDS** [comment] 2021-01-06 09:05
> We had the idea that it could be some wierd concurrency issues, and jose merged a PR that brings some fixes from upstream. If there are some other wierd concurrency problems on PN's code please point those out so we can fix them, and by consequence of that close this issue.

As I said earlier, there is a possibility that packets will be encoded in parallel, writing data in different threads to the same buffer producing garbage. With a PR #882 this aspect of encoding has not been touched in any way. The only solution I see is to encode it on the main thread before pushing to queue, or use blocking IO, or clone the packet.

Just tested current bleeding-1.3 (db5a9e7), the problem is still there. The server sends garbage packet and the client disconnects. Packet buffer: ```120f0f000099031143d7a38242d7a38242000000007f96964200dddd```

Also reproduce steps:
1. Install MobPlugin (Nukkit-coders/MobPlugin#04ac813)
2. Join from different accounts and be at the same position
3. Wait for mobs
4. If still not disconnected, re-join from one of the accounts (seems you have two connections on the same thread)

**Comment by RORIdev** [comment] 2021-01-06 18:34
> > We had the idea that it could be some wierd concurrency issues, and jose merged a PR that brings some fixes from upstream. If there are some other wierd concurrency problems on PN's code please point those out so we can fix them, and by consequence of that close this issue.
> 
> As I said earlier, there is a possibility that packets will be encoded in parallel, writing data in different threads to the same buffer producing garbage. With a PR #882 this aspect of encoding has not been touched in any way. The only solution I see is to encode it on the main thread before pushing to queue, or use blocking IO, or clone the packet.
> 
> Just tested current bleeding-1.3 ([db5a9e7](https://github.com/PowerNukkit/PowerNukkit/commit/db5a9e730161a71396dd8321d9941aa734372e1a)), the problem is still there. The server sends garbage packet and the client disconnects. Packet buffer: `120f0f000099031143d7a38242d7a38242000000007f96964200dddd`
> 
> Also reproduce steps:
> 
> 1. Install MobPlugin (Nukkit-coders/MobPlugin#04ac813)
> 2. Join from different accounts and be at the same position
> 3. Wait for mobs
> 4. If still not disconnected, re-join from one of the accounts (seems you have two connections on the same thread)

Thing with "pn breaks if plugin" since we mainly develop pn is, if pn doesn't break alone we won't ever be able to know, unless we test every version of every plugin before every single release.

That kinda work for the small size of the core team that we have its just not feasible. This sort of bug, if its not possible to replicate on PN without any plugins should be sent as a Plugin Issue, with the version of pn and the plugin tested so that we try to see why there's an incompatibility with said plugin and *try* to fix that on our end, if the plugin then breaks again we have to go to the same process again.

[PowerNukkit-Test-Server](http://github.com/powernukkit/PowerNukkit-Test-Server) is trying to bridge that gap, and its one of the projects being worked on in order to make this process more efficient and open.

**Comment by AntonPPDS** [comment] 2021-01-06 18:47
> Thing with "pn breaks if plugin" since we mainly develop pn is, if pn doesn't break alone we won't ever be able to know, unless we test every version of every plugin before every single release.
> 
> That kinda work for the small size of the core team that we have its just not feasible. This sort of bug, if its not possible to replicate on PN without any plugins should be sent as a Plugin Issue, with the version of pn and the plugin tested so that we try to see why there's an incompatibility with said plugin and _try_ to fix that on our end, if the plugin then breaks again we have to go to the same process again.
> 
> [PowerNukkit-Test-Server](https://github.com/powernukkit/PowerNukkit-Test-Server) is trying to bridge that gap, and its one of the projects being worked on in order to make this process more efficient and open.

IMHO this a bit is more of a server issue than a plugin. I found out that the problem comes from [this](https://github.com/Nukkit-coders/MobPlugin/blob/04ac8134b0f1db39675c31af01f93521c3c53104/src/main/java/nukkitcoders/mobplugin/entities/BaseEntity.java#L477-L479) piece of code. Instead of using broadcast method which encodes packet before putting it to the interface (so that why PN itself has no problem), plugin iterates players and sends packet using Player#batchDataPacket() method. Concurrency issues are not really expected to occur when using such code.

**Comment by RORIdev** [comment] 2021-01-06 18:51
> > Thing with "pn breaks if plugin" since we mainly develop pn is, if pn doesn't break alone we won't ever be able to know, unless we test every version of every plugin before every single release.
> > That kinda work for the small size of the core team that we have its just not feasible. This sort of bug, if its not possible to replicate on PN without any plugins should be sent as a Plugin Issue, with the version of pn and the plugin tested so that we try to see why there's an incompatibility with said plugin and _try_ to fix that on our end, if the plugin then breaks again we have to go to the same process again.
> > [PowerNukkit-Test-Server](https://github.com/powernukkit/PowerNukkit-Test-Server) is trying to bridge that gap, and its one of the projects being worked on in order to make this process more efficient and open.
> 
> IMHO this a bit is more of a server issue than a plugin. I found out that the problem comes from [this](https://github.com/Nukkit-coders/MobPlugin/blob/04ac8134b0f1db39675c31af01f93521c3c53104/src/main/java/nukkitcoders/mobplugin/entities/BaseEntity.java#L477-L479) piece of code. Instead of using broadcast method which encodes packet before putting it to the interface (so that why PN itself has no problem), plugin iterates players and sends packet using Player#batchDataPacket() method. Concurrency issues are not really expected to occur when using such code.

Thanks for your patience and report, now we can look on that and fix it in our side.

**Comment by RORIdev** [comment] 2021-01-06 20:14
As this issue is marked as solve i'll close until something on pn alone breaks completely.
I'll also make an issue about plugin compatibility with mobplugin.

**Closed by RORIdev** 2021-01-06 20:14 UTC
Labels: Resolution: resolved, Type: bug
