### ISSUE TITLE
Stairs

### ISSUE THREAD

**Issue by TheDiego845** [PowerNukkit/PowerNukkit#1157] opened 2021-06-26 17:56 UTC
I found a big bug in gamemode survival  when I am putting stairs the stairs turn around it is very annoying.

 PowerNukkit version: 1.5.1.0-PN-SNAPSHOT

**Comment by joserobjr** [comment] 2021-06-27 17:24
On which device and which control type are you using? (keyboard and mouse, keyboard-only, xbox controller, touch screen without a cross in the middle, touch screen with a cross in the middle)

**Comment by TheDiego845** [comment] 2021-06-27 18:35
touch screen normal

**Comment by joserobjr** [comment] 2021-06-27 18:37
like what happens in this video?

https://user-images.githubusercontent.com/3679022/123555654-69afee80-d75d-11eb-86a6-9dfaa5a86704.mp4

**Comment by TheDiego845** [comment] 2021-06-27 18:42
yes

**Comment by joserobjr** [comment] 2021-06-27 18:46
I'm going to close this issue as a duplicate of #696, as a workaround, you can enable in your game: Settings -> Touch -> Split Controls, I'll try to fix it up to 1.5.2.0-PN, it doesn't seem to be that hard to fix

**Closed by joserobjr** 2021-06-27 18:46 UTC
Labels: Type: bug
