### ISSUE TITLE
Command blocks

### ISSUE THREAD

**Issue by MrCrazyMan109** [PowerNukkit/PowerNukkit#1001] opened 2021-03-20 00:00 UTC
# ❇ Feature Request

It would be pretty nice if command blocks could be implemented into PowerNukkit. It makes life a lot easier :) 
(well, at least for me.)

Thank you!

https://debugpaste.powernukkit.org/pastes/PN43bd2260/

**Comment by Superzock3003** [comment] 2021-03-20 00:18
Hey @MrCrazyMan109! There is already a plugin for commandblocks, if you really need them: https://github.com/wode490390/VanillaCommandBlock/releases/tag/1.0.0

**Comment by GoodLucky777** [comment] 2021-03-20 00:27
Duplicated with #122

**Comment by LoboMetalurgico** [comment] 2021-03-20 00:30
Closed. Reason: Duplicate of issue #122

**Closed by LoboMetalurgico** 2021-03-20 00:30 UTC
Labels: Type: enhancement
