### ISSUE TITLE
обновите nether

### ISSUE THREAD

**Issue by feanchy** [PowerNukkit/PowerNukkit#1364] opened 2022-06-24 20:33 UTC
add a new nether

**Comment by LoboMetalurgico** [comment] 2022-07-03 02:32
Duplicate of #1230.

**Closed as not planned by LoboMetalurgico** 2022-07-03 02:32 UTC
Labels: Resolution: duplicate, Type: enhancement

**Comment by feanchy** [comment] 2022-07-03 05:46
> Дубликат [№ 1230](https://github.com/PowerNukkit/PowerNukkit/issues/1230) .

reminder
