### ISSUE TITLE
Player Disconnect 

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#896] opened 2021-01-07 21:01 UTC
# 🐞 I found a bug
 Heyho, there is another Disconnect Problem but without Errors.
I Join my Server at the Main Spawn Point (Set with /setspawn) 
When another Player joined my Server at the Same Chunk in this Main Spawn Point, i get a Disconnect from Server.
Its really weird and hard to reproduce this Issue.
At this time, 3 Players was online at Same time for Testing.
[36m21:57:48[m [[m[31mWARN [m[m] Violation warning from CardiiiPvP for packet SET_ENTITY_MOTION_PACKET: PacketViolationWarningPacket(type=MALFORMED_PACKET, severity=FINAL_WARNING, packetId=40, context=)

### ▶ Steps to Reproduce

1. Let Players Join at Servers Mainspawn
2. Get a Disconnect
3. See Error 
4. Many Players have this Issue on my server

### 📋 Debug information

* PowerNukkit version: (git-66f87fe)
* Debug link: (git-66f87fe)
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment] 2021-01-07 21:02
Ups, sorry /debugpaste doesnt work at this time

**Comment by MonoAdrian23** [comment] 2021-01-09 09:52
3 Players at Same Time works, but when joins a 4th Player, all other get kicked

**Comment by Verox001** [comment] 2021-01-09 11:21
Yes! I have this problem too.

Not just with PowerNukkit. With Nukkit I have the same problem.

**Comment by Verox001** [comment] 2021-01-09 11:23
Please fix this. This also happens on my server when two players are in the same chunk. And I get the same warning.

**Comment by RORIdev** [comment] 2021-01-09 18:10
> 3 Players at Same Time works, but when joins a 4th Player, all other get kicked

> Yes! I have this problem too.
> 
> Not just with PowerNukkit. With Nukkit I have the same problem.

Good to know.  I'll put this issue on a higher priority

**Comment by djmaisen** [comment] 2021-01-17 13:36
I have the same problem. 2 Players is okay, 3 Player and the other kickt.

**Comment by MonoAdrian23** [comment] 2021-01-17 16:25
I think really this is a plugin Issue.

**Comment by Verox001** [comment] 2021-01-17 17:28
No. I tested it without plugins and resetted the server, but I still have the issue.

**Comment by ZandercraftGames** [comment] 2021-02-03 16:40
This issue happens on my servers also.

**Comment by PleaseInsertNameHere** [comment] 2021-02-03 16:57
I've got that issue too. Unfortunately, resetting the server did not help.

**Comment by MonoAdrian23** [comment] 2021-02-03 17:08
PowerNukkit Devs does nothing, no fix for Chunkload, no fix for this Issue, no fixes for another Issues.
I think this Software is Death.

**Comment by PleaseInsertNameHere** [comment] 2021-02-03 17:21
Yes, but actually no. Since anyone can contribute to PowerNukkit, we could fix it ourselves.

**Comment by ZandercraftGames** [comment] 2021-02-03 23:18
> Yes, but actually no. Since anyone can contribute to PowerNukkit, we could fix it ourselves.

Agreed. Does anyone have any idea what's causing it? Any debug logs?

**Comment by Aenoxic** [comment] 2021-02-11 14:57
Possibly a RakNet issue, which is caused. With NukkitX the issue is not present. Any proxies are not affected.

**Comment by MonoAdrian23** [comment] 2021-02-11 15:22
Thats Not correct, NukkitX have's the Same issue for many weeks.

**Comment by Aenoxic** [comment] 2021-02-11 16:20
And why should this not get fixed within these "many weeks"?

**Closed** 2021-03-29 08:56 UTC
Labels: Tag : Minecraft Version Update, Type: bug, Type: compatibility

**Comment by ZandercraftGames** [comment] 2021-03-29 19:03
Was this closed because the issue was fixed?

**Comment by RORIdev** [comment] 2021-03-29 20:40
No idea, @MonoAdrian23 closed a bunch of issues today and even us are confused.
If you're gonna close stuff state the reason.

**Comment by MonoAdrian23** [comment] 2021-03-30 04:33
Yes, that was the Disconnect Bug.
It's fixed
