### ISSUE TITLE
Snow logging

### ISSUE THREAD

**Issue by PocketMiner82** [PowerNukkit/PowerNukkit#876] opened 2020-12-29 18:29 UTC
# ❇ Feature Request
Snow logging is not implemented.

### ✔ Expected Behavior
Place snow layer on e.g. grass, the snow should be there and the grass too.

### ❌ Actual Behavior
It works only client side; but if you rejoin, there is only the snow layer left, so the server doesn't know it's snow logged.

### Debug:
1.4; https://github.com/PowerNukkit/PowerNukkit/commit/b00df764562a3f8a04b2a09c551912417b1a5691

**Comment by PocketMiner82** [comment] 2020-12-29 18:30
1.4; https://github.com/PowerNukkit/PowerNukkit/commit/b00df764562a3f8a04b2a09c551912417b1a5691

**Comment by GoodLucky777** [comment] 2022-07-10 13:58
Duplicate of #611

**Closed** 2022-07-11 18:21 UTC
Labels: Type: enhancement
