### ISSUE TITLE
add algae, corals, etc. and generally update the generation of waters

### ISSUE THREAD

**Issue by feanchy** [PowerNukkit/PowerNukkit#1375] opened 2022-07-05 16:43 UTC
# ❇ Feature Request

### 📸 Screenshots / Videos
https://youtu.be/lejchu9Z-KE

### ✔ Expected Behavior
algae, corals are in powernukkit generation

### ❌ Actual Behavior
there are none

**Comment by GoodLucky777** [comment] 2022-07-10 02:57
Duplicate of #584

**Closed as not planned** 2022-07-10 03:23 UTC
Labels: Resolution: duplicate, Type: enhancement
