### ISSUE TITLE
Grindstone doenst work

### ISSUE THREAD

**Issue by PocketMiner92** [PowerNukkit/PowerNukkit#1292] opened 2022-01-09 08:46 UTC
# 🐞 I found a bug
 The Recipes for Grindstone doesnt work.
Same with Armor Stand.
And you cant remove Enchantments with a Grindstone.

### ▶ Steps to Reproduce

1. Run command '...'
3. Put '....' at '...'

### 📋 Debug information

* PowerNukkit version: (git-70f88e5)
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by alikindsys** [comment] 2022-06-30 05:33
Duplicate of #1208

**Closed by alikindsys** 2022-06-30 05:33 UTC
Labels: Resolution: duplicate
