### ISSUE TITLE
The iron bucket milking bucket will disappear

### ISSUE THREAD

**Issue by whes1015** [PowerNukkit/PowerNukkit#1165] opened 2021-06-29 09:44 UTC
# 🐞 I found a bug

### ▶ Steps to Reproduce

1.The iron bucket milking bucket will disappear

### 📋 Debug information

* PowerNukkit version:1.5-PN-MC1.17.0-B80 ✍
* Debug link: ✍
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment] 2021-06-29 09:51
If you use MobPlugin?

**Comment by whes1015** [comment] 2021-06-29 09:54
I am using

> 如果你使用 MobPlugin？

I am using

**Comment by Superzock3003** [comment] 2021-06-29 09:55
Its an Mobplugin Error

**Comment by MonoAdrian23** [comment] 2021-06-29 09:55
Its a confirmed issue in MobPlugin. 
Only Gamemode Creative Buckets works

**Comment by GoodLucky777** [comment] 2021-07-01 09:09
I fixed it in https://github.com/Nukkit-coders/MobPlugin/pull/231

**Comment by whes1015** [comment] 2021-07-07 15:38
> 我在[Nukkit-coders/MobPlugin#231 中](https://github.com/Nukkit-coders/MobPlugin/pull/231)修復了它[](https://github.com/Nukkit-coders/MobPlugin/pull/231)

got it

**Comment by MonoAdrian23** [comment] 2021-07-07 15:55
You can close this because its fixed

**Closed** 2021-10-24 02:13 UTC
Labels: Type: bug, Resolution: resolved
