### ISSUE TITLE
I think PowerNukkit should have a built in one player sleep system that can be turned on or off in the server.properties files.

### ISSUE THREAD

**Issue by MrRazamataz** [PowerNukkit/PowerNukkit#304] opened 2020-06-29 13:24 UTC
I think PowerNukkit should have a built in one player sleep system that can be turned on or off in the server.properties files because all the plugins that I have found are terrible at it. Or let me know if you have found a good one.

**Comment by Jl1mbo** [comment] 2020-06-29 16:40
I do not understand a little what exactly you want

**Comment by MrRazamataz** [comment] 2020-06-29 16:54
@Jl1mbo Like an option that when you turn it on it means that if 1 player goes in a bed with multiple players online, it goes to day along with the normal bed behaviour (setting player spawn).

**Comment by tuilakhanh** [comment] 2020-06-29 16:57
Player time ?

**Comment by MrRazamataz** [comment] 2020-06-29 17:03
If I'm correct on what you are saying, no. Its set the time for the whole server.

**Comment by joserobjr** [comment] 2020-07-15 12:54
Hello, I've been thinking on this suggestion. Unfortunately I'm going to close it with wontfix. The reason is because PowerNukkit must reproduce the most closed to vanilla behaviour as possible. Since it's not a vanilla game mechanic, it should not come builtin.

Plugins can do this easily though. My suggestion is to use an existing plugin which does that, make, or request one.

May be you could open the plugin section on our new discussion board with your plugin request. If you share what you expect from the plugin in a new thread there I could try to make it.
https://discuss.powernukkit.org/c/plugins/6

**Closed** 2020-07-15 12:54 UTC
Labels: Resolution: wontfix, Type: enhancement

**Comment by MrRazamataz** [comment] 2020-07-19 01:18
Ok that's fine. I'm trying to make my own plugin for it.
