### ISSUE TITLE
Loom doenst work

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#807] opened 2020-12-07 11:23 UTC
# 🐞 I found a bug
 

### ▶ Steps to Reproduce

1. Place a Loom
2. Click on Loom
3. There is no Interface for it

### 📋 Debug information

* PowerNukkit version: 1.4.0.0 Alpha 2
* Debug link: https://debugpaste.powernukkit.org/pastes/jacumoyera
* Timings link (if relevant): ✍

**Comment by MrRazamataz** [comment] 2020-12-07 11:37
Duplicate of #422

**Closed** 2021-12-07 10:53 UTC
Labels: Type: enhancement, Implementation: Block, Implementation: BlockEntity
