### ISSUE TITLE
Stair Block Placing is buggy

### ISSUE THREAD

**Issue by MonoAdrian23** [PowerNukkit/PowerNukkit#859] opened 2020-12-23 09:05 UTC
# 🐞 I found a bug
 When placing a stair block, the orientation is not correct. It doesn't happen often, so it doesn't really matter

### ▶ Steps to Reproduce

1. Place a Stair Block

### 📋 Debug information

* PowerNukkit version: 1.4.0.0 Alpha 2
* Debug link: https://debugpaste.powernukkit.org/pastes/ijuderoful
* Timings link (if relevant): ✍

**Comment by MonoAdrian23** [comment] 2020-12-23 09:14
![20201223_095524.jpg](https://user-images.githubusercontent.com/59027482/102980237-8bf35600-4507-11eb-97b2-33e0a3414a56.jpg)

**Comment by RORIdev** [comment] 2021-01-03 15:31
Duplicate of #696

**Closed by RORIdev** 2021-01-03 15:31 UTC
Labels: Type: bug
