### ISSUE TITLE
When the player is rowing on the sea, the boat will gradually fly

### ISSUE THREAD

**Issue by SS-YG** [PowerNukkit/PowerNukkit#873] opened 2020-12-29 13:26 UTC
When the player is rowing on the sea, the boat will gradually fly

https://debugpaste.powernukkit.org/pastes/akaqibomik

**Comment by MonoAdrian23** [comment] 2020-12-29 13:51
Duplicate of #853

**Closed** 2021-01-03 15:28 UTC
Labels: Resolution: duplicate, Type: bug
