### ISSUE TITLE
Can't craft torches with charcoal

### ISSUE THREAD

**Issue by IrineuMC** [PowerNukkit/PowerNukkit#793] opened 2020-11-28 15:12 UTC
# 🐞 I found a bug
**Can't craft torches with charcoal**

### 📋 Debug information
* PowerNukkit version: 1.4.0.0-PN-ALPHA.2-SNAPSHOT

**Comment by MrRazamataz** [comment] 2020-11-28 16:46
Duplicate of #781 .

**Closed** 2020-12-06 20:21 UTC
Labels: Resolution: duplicate, Type: bug
